import type {
  AiJsonProvider,
  AiJsonRequest
} from "../../apps/worker/src/services/report-generation/ai/ai-provider.js";

export class DeterministicAiJsonProviderMock implements AiJsonProvider {
  readonly providerName = "deterministic-test";
  readonly model = "test-model";

  async generateJson(_request: AiJsonRequest): Promise<unknown> {
    return {
      executiveSummary: "Deterministic test executive summary",
      keyRisks: ["High-risk findings require review"],
      recommendations: [
        {
          priority: "high",
          title: "Review high-risk findings",
          detail: "Generated by deterministic test provider"
        }
      ]
    };
  }
}
