import { Router } from "express";
import { authRoutes } from "../../modules/auth/auth.routes.js";
import { healthRoutes } from "../../modules/health/health.routes.js";
import { organizationRoutes } from "../../modules/organizations/organizations.routes.js";
import { scanRoutes } from "../../modules/scans/scans.routes.js";
import { publicReportRoutes, reportRoutes } from "../../modules/reports/reports.routes.js";
import { vulnerabilityRoutes } from "../../modules/vulnerabilities/vulnerabilities.routes.js";
import { findingRoutes } from "../../modules/findings/findings.routes.js";
import { projectRoutes } from "../../modules/projects/projects.routes.js";
import { apiKeyRoutes } from "../../modules/api-keys/api-keys.routes.js";
import { subscriptionRoutes } from "../../modules/subscriptions/subscriptions.routes.js";
import { remediationRoutes } from "../../modules/remediation/remediation.routes.js";
import { simulationRoutes } from "../../modules/simulations/simulation.routes.js";
import { fuzzingRoutes } from "../../modules/fuzzing/fuzzing.routes.js";
import { monitoringRoutes } from "../../modules/monitoring/monitoring.routes.js";
import { threatKnowledgeRoutes } from "../../modules/threat-knowledge/threat.routes.js";
import { enterpriseRoutes } from "../../modules/enterprise/enterprise.routes.js";
import { githubIntegrationRoutes, githubWebhookRoutes } from "../../modules/github/github.routes.js";
import { sourceIngestionRoutes } from "../../modules/source-ingestion/source-ingestion.routes.js";
import { billingRoutes, billingWebhookRoutes } from "../../modules/billing/billing.routes.js";
import { securityOsRoutes } from "../../modules/security-os/security-os.routes.js";
import { chainsRoutes } from "../../modules/chains/chains.routes.js";

export const v1Router = Router();

v1Router.use(healthRoutes);
v1Router.use("/auth", authRoutes);
v1Router.use(githubWebhookRoutes);
v1Router.use(billingWebhookRoutes);
v1Router.use("/organizations/:organizationId/api-keys", apiKeyRoutes);
v1Router.use("/organizations/:organizationId/subscriptions", subscriptionRoutes);
v1Router.use("/organizations", organizationRoutes);
v1Router.use("/public/reports", publicReportRoutes);
v1Router.use("/scans", scanRoutes);
v1Router.use("/reports", reportRoutes);
v1Router.use("/findings", findingRoutes);
v1Router.use("/remediations", remediationRoutes);
v1Router.use("/simulations", simulationRoutes);
v1Router.use("/fuzz-runs", fuzzingRoutes);
v1Router.use(monitoringRoutes);
v1Router.use(threatKnowledgeRoutes);
v1Router.use(enterpriseRoutes);
v1Router.use(githubIntegrationRoutes);
v1Router.use(sourceIngestionRoutes);
v1Router.use(billingRoutes);
v1Router.use(securityOsRoutes);
v1Router.use(chainsRoutes);
v1Router.use("/projects", projectRoutes);
v1Router.use("/vulnerabilities", vulnerabilityRoutes);
