-- Phase P13 hotfix: prepare enum values before billing tables use them.
-- PostgreSQL cannot use a freshly added enum value in the same transaction.
-- Keep this migration separate and earlier than 20260525170000_p13_billing.

ALTER TYPE "SubscriptionStatus" ADD VALUE IF NOT EXISTS 'INCOMPLETE';
ALTER TYPE "SubscriptionStatus" ADD VALUE IF NOT EXISTS 'FREE_BETA';
ALTER TYPE "SubscriptionStatus" ADD VALUE IF NOT EXISTS 'MANUAL_OVERRIDE';

ALTER TYPE "UsageMetric" ADD VALUE IF NOT EXISTS 'SOURCE_ARTIFACTS_PER_MONTH';
ALTER TYPE "UsageMetric" ADD VALUE IF NOT EXISTS 'GITHUB_SCANS_PER_MONTH';
ALTER TYPE "UsageMetric" ADD VALUE IF NOT EXISTS 'CLI_SCANS_PER_MONTH';
ALTER TYPE "UsageMetric" ADD VALUE IF NOT EXISTS 'SIMULATIONS_PER_MONTH';
ALTER TYPE "UsageMetric" ADD VALUE IF NOT EXISTS 'FUZZ_RUNS_PER_MONTH';
ALTER TYPE "UsageMetric" ADD VALUE IF NOT EXISTS 'THREAT_MATCHES_PER_MONTH';
ALTER TYPE "UsageMetric" ADD VALUE IF NOT EXISTS 'API_KEYS_MAX';
ALTER TYPE "UsageMetric" ADD VALUE IF NOT EXISTS 'TEAM_MEMBERS_MAX';
ALTER TYPE "UsageMetric" ADD VALUE IF NOT EXISTS 'REPO_CONNECTIONS_MAX';
ALTER TYPE "UsageMetric" ADD VALUE IF NOT EXISTS 'WEBHOOKS_MAX';
