DO $$ BEGIN
  ALTER TYPE "SecurityOsArtifactType" ADD VALUE IF NOT EXISTS 'FORMAL_TOOL_ADAPTER';
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TYPE "SecurityOsArtifactType" ADD VALUE IF NOT EXISTS 'AUDITOR_ONBOARDING';
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TYPE "SecurityOsArtifactType" ADD VALUE IF NOT EXISTS 'CUSTOMER_PILOT';
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TYPE "SecurityOsArtifactType" ADD VALUE IF NOT EXISTS 'PUBLIC_TRACK_RECORD';
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TYPE "SecurityOsArtifactType" ADD VALUE IF NOT EXISTS 'LEGAL_COMPLIANCE_OPERATION';
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TYPE "SecurityOsArtifactType" ADD VALUE IF NOT EXISTS 'OPERATIONS_RUNBOOK';
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
