import { describe, expect, it } from "vitest";
import { promises as fs } from "node:fs";

describe("Prisma schema contract", () => {
  it("declares the scan persistence models", async () => {
    const schema = await fs.readFile("packages/database/prisma/schema.prisma", "utf8");

    expect(schema).toContain("model Scan ");
    expect(schema).toContain("model ScanTarget ");
    expect(schema).toContain("model Vulnerability ");
    expect(schema).toContain("model AuditReport ");
    expect(schema).toContain("@@index([status, priority, queuedAt])");
    expect(schema).toContain("enum FindingConfidenceState");
    expect(schema).toContain("model FindingEvidence ");
    expect(schema).toContain("model SourceRange ");
    expect(schema).toContain("model AnalyzerEvidence ");
    expect(schema).toContain("model FindingDecision ");
    expect(schema).toContain("model DetectorMetadata ");
    expect(schema).toContain("enum FindingReviewStatus");
    expect(schema).toContain("enum FindingReviewAction");
    expect(schema).toContain("model Project ");
    expect(schema).toContain("model FindingReview ");
    expect(schema).toContain("model FindingReviewEvent ");
    expect(schema).toContain("model FindingSuppressionRule ");
    expect(schema).toContain("model FindingBaseline ");
    expect(schema).toContain("model FindingComment ");
    expect(schema).toContain("model FindingAssignment ");
    expect(schema).toContain("model CodeOwnerRule ");
    expect(schema).toContain("enum ExtractionStatus");
    expect(schema).toContain("model AnalysisIrRun ");
    expect(schema).toContain("model ContractSymbol ");
    expect(schema).toContain("model FunctionSymbol ");
    expect(schema).toContain("model ModifierSymbol ");
    expect(schema).toContain("model StateVariableSymbol ");
    expect(schema).toContain("model EventSymbol ");
    expect(schema).toContain("model CallGraphEdge ");
    expect(schema).toContain("model ExternalCallSite ");
    expect(schema).toContain("model StorageLayoutEntry ");
    expect(schema).toContain("model SourceMapEntry ");
    expect(schema).toContain("model FindingCodeLink ");
    expect(schema).toContain("enum BuildToolKind");
    expect(schema).toContain("enum BuildRunStatus");
    expect(schema).toContain("enum TestRunStatus");
    expect(schema).toContain("model BuildProfile ");
    expect(schema).toContain("model BuildRun ");
    expect(schema).toContain("model CompilerArtifact ");
    expect(schema).toContain("model TestRun ");
    expect(schema).toContain("model TestResult ");
    expect(schema).toContain("model AnalyzerToolAvailability ");
    expect(schema).toContain("enum AiValidationStatus");
    expect(schema).toContain("enum AiValidationDecision");
    expect(schema).toContain("enum AiValidationScope");
    expect(schema).toContain("model AiValidationRun ");
    expect(schema).toContain("model AiFindingValidation ");
    expect(schema).toContain("model AiEvidenceCritique ");
    expect(schema).toContain("model AiReviewNote ");
    expect(schema).toContain("model AiProviderUsage ");
    expect(schema).toContain("enum RemediationStatus");
    expect(schema).toContain("enum RemediationKind");
    expect(schema).toContain("enum PatchSafetyStatus");
    expect(schema).toContain("model RemediationRun ");
    expect(schema).toContain("model RemediationSuggestion ");
    expect(schema).toContain("model RemediationDiff ");
    expect(schema).toContain("model RemediationTestSuggestion ");
    expect(schema).toContain("model RemediationChecklistItem ");
    expect(schema).toContain("model RemediationReviewEvent ");
    expect(schema).toContain("enum ReportStatus");
    expect(schema).toContain("enum ReportExportFormat");
    expect(schema).toContain("model Report ");
    expect(schema).toContain("model ReportSection ");
    expect(schema).toContain("model ReportExport ");
    expect(schema).toContain("model ReportShareLink ");
    expect(schema).toContain("model ReportDisclaimer ");
    expect(schema).toContain("model ReportGenerationRun ");
    expect(schema).toContain("enum SimulationStatus");
    expect(schema).toContain("enum SimulationKind");
    expect(schema).toContain("enum SimulationSafetyLevel");
    expect(schema).toContain("model SimulationRun ");
    expect(schema).toContain("model SimulationPlan ");
    expect(schema).toContain("model SimulationStep ");
    expect(schema).toContain("model SimulationTrace ");
    expect(schema).toContain("model SimulationAssetDelta ");
    expect(schema).toContain("model SimulationEligibility ");
    expect(schema).toContain("model SimulationArtifact ");
    expect(schema).toContain("model SimulationDecision ");
    expect(schema).toContain("enum FuzzRunStatus");
    expect(schema).toContain("enum FuzzToolKind");
    expect(schema).toContain("enum InvariantStatus");
    expect(schema).toContain("model FuzzRun ");
    expect(schema).toContain("model FuzzTarget ");
    expect(schema).toContain("model FuzzTestCase ");
    expect(schema).toContain("model FuzzCounterexample ");
    expect(schema).toContain("model InvariantRun ");
    expect(schema).toContain("model InvariantDefinition ");
    expect(schema).toContain("model InvariantResult ");
    expect(schema).toContain("model CoverageSummary ");
    expect(schema).toContain("model FuzzArtifact ");
    expect(schema).toContain("enum MonitorStatus");
    expect(schema).toContain("enum MonitorTargetKind");
    expect(schema).toContain("enum MonitorRuleKind");
    expect(schema).toContain("enum MonitorEventStatus");
    expect(schema).toContain("enum AlertSeverity");
    expect(schema).toContain("enum AlertStatus");
    expect(schema).toContain("model MonitorTarget ");
    expect(schema).toContain("model MonitorRule ");
    expect(schema).toContain("model MonitorRun ");
    expect(schema).toContain("model MonitorCursor ");
    expect(schema).toContain("model OnchainEvent ");
    expect(schema).toContain("model OnchainTransaction ");
    expect(schema).toContain("model MonitorAlert ");
    expect(schema).toContain("model AlertEvidence ");
    expect(schema).toContain("model AlertComment ");
    expect(schema).toContain("model AlertStatusEvent ");
    expect(schema).toContain("model AlertWebhookDelivery ");
    expect(schema).toContain("model ProjectWebhook ");
    expect(schema).toContain("enum EnterpriseRoleType");
    expect(schema).toContain("enum ApiKeyAuditAction");
    expect(schema).toContain("enum AccessAuditDecision");
    expect(schema).toContain("enum DataRequestStatus");
    expect(schema).toContain("enum SsoConnectionStatus");
    expect(schema).toContain("model Team ");
    expect(schema).toContain("model TeamMember ");
    expect(schema).toContain("model ProjectMember ");
    expect(schema).toContain("model ApiKeyAuditEvent ");
    expect(schema).toContain("model AccessAuditLog ");
    expect(schema).toContain("model DataRetentionPolicy ");
    expect(schema).toContain("model DataExportRequest ");
    expect(schema).toContain("model DataDeletionRequest ");
    expect(schema).toContain("model SsoConnection ");
    expect(schema).toContain("model SsoLoginAttempt ");
    expect(schema).toContain("model SecuritySetting ");
    expect(schema).toContain("model AdminActionEvent ");
    expect(schema).toContain("enum RepositoryIntegrationProvider");
    expect(schema).toContain("enum GitHubInstallationStatus");
    expect(schema).toContain("enum GitHubRepositoryStatus");
    expect(schema).toContain("enum GitHubWebhookEventStatus");
    expect(schema).toContain("enum IntegrationScanSource");
    expect(schema).toContain("enum IntegrationScanStatus");
    expect(schema).toContain("model GitHubInstallation ");
    expect(schema).toContain("model GitHubRepository ");
    expect(schema).toContain("model GitHubWebhookEvent ");
    expect(schema).toContain("model RepositoryScan ");
    expect(schema).toContain("model CiRun ");
    expect(schema).toContain("model CliScanEvent ");
    expect(schema).toContain("enum SourceArtifactStatus");
    expect(schema).toContain("enum SourceOriginKind");
    expect(schema).toContain("enum SourcePolicyStatus");
    expect(schema).toContain("model SourceArtifact ");
    expect(schema).toContain("model SourceManifest ");
    expect(schema).toContain("model SourceFileEntry ");
    expect(schema).toContain("model SourceIngestionRun ");
    expect(schema).toContain("model SourceIngestionError ");
    expect(schema).toContain("model RepositorySourceSnapshot ");
    expect(schema).toContain("model CliSourceUpload ");
    expect(schema).toContain("model SourcePolicyDecision ");
    expect(schema).toContain("enum ThreatIntelSourceType");
    expect(schema).toContain("enum ThreatIntelConfidence");
    expect(schema).toContain("enum ThreatSignatureKind");
    expect(schema).toContain("enum ThreatMatchStatus");
    expect(schema).toContain("model ThreatIntelEntry ");
    expect(schema).toContain("model ThreatSource ");
    expect(schema).toContain("model ThreatSignature ");
    expect(schema).toContain("model ThreatSignatureCondition ");
    expect(schema).toContain("model ThreatSignatureMatch ");
    expect(schema).toContain("model DetectorPrecisionMetric ");
    expect(schema).toContain("model FalsePositiveFeedback ");
    expect(schema).toContain("model VulnerabilityPattern ");
    expect(schema).toContain("model IncidentReference ");
    expect(schema).toContain("model WalletRiskLabel ");
    expect(schema).toContain("model ContractRiskLabel ");
    expect(schema).toContain("model ThreatKnowledgeRevision ");
    expect(schema).toContain("enum PlanTier");
    expect(schema).toContain("enum UsageMetric");
    expect(schema).toContain("model Plan ");
    expect(schema).toContain("model UsageCounter ");
    expect(schema).toContain("model UsageEvent ");
  });
});
